### ISSUE TITLE
Implicit declaration of function 'lorgnette_lookup_baseaddress' is invalid in C99

### ISSUE THREAD

**Issue by gloxec** [MTJailed/UnjailMe#17]
'lorgnette_lookup_image'  ?

**Comment by MTJailed** [comment]
You're right. I'll commit tomorrow fixing your issue ;)

**Comment by MTJailed** [comment]
lorgnette_lookup_image is something else, so please wait till my next commit

**Comment by MTJailed** [comment]
The issue should be fixed now ;)
